import { Toaster } from "@/components/ui/toaster";
import { Inter } from "next/font/google";
import Footer from "./_components/footer";
import Navbar from "./_components/navbar";
import { AuthProvider } from "./_providers/useAuth";
import { CartProvider } from "./_providers/useCart";
import "./globals.css";

export const dynamic = "force-dynamic";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + "overflow-x-hidden flex flex-col min-h-screen "
        }>
        <AuthProvider>
          <CartProvider>
            <Navbar />
            <main className="flex-grow px-8 py-4">{children}</main>
            <Toaster />
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
